Iter20
keyjin88/shortener pull request #20
Opened 2023-08-25 07:19 UTC by keyjin88

2023-09-06 06:37 UTC, s-shpak requested changes
Пожалуйста, добавь в проект `golangci-lint`, здесь описано как: https://github.com/s-shpak/praktikum-golangci-lint.git

Все его замечания править сразу необязательно, но их надо будет учесть. Если ты захочешь обсудить какие-то конкретные правила, то пиши. Также ты можешь подстроить конфигурацию под себя

2023-09-06 06:37 UTC, s-shpak commented on cmd/staticlint/main.go
> +		callExpr := node.(*ast.CallExpr)
Здесь лучше проверить валидность type assertion

2023-09-06 10:42 UTC, keyjin88 commented on cmd/staticlint/main.go
> +		callExpr := node.(*ast.CallExpr)
Линтер подключил. Его, кстати, можно как плагин в GoLand добавить. Что я и сделал после.

2023-09-10 06:48 UTC, s-shpak approved these changes

2023-09-11 06:51 UTC, merged