complete iteration #5
keyjin88/shortener pull request #5
Opened 2023-04-30 16:47 UTC by keyjin88

2023-05-01 20:34 UTC, maxlyaptsev requested changes
Первым делом нужно исправить логику - если сделать несколько коротких url, работать будет только один

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +package storage
Не очерь понятно назначение структуры Storage. Если для упрощения Dependency injection, то это наоборот создает неопреденность - не понятно какой именно репозиторий будет нужен в сервисе - лучше явно передвать конкретный репозитоирий

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +		storage: s,
неправильно делать такие циклические зависимости - репозиторий через storage сможет вызвать сам себя

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/storage/urlrepository.go
> +	for shortenStr, url := range inmemStorage {
Получается очень высокая алгоритмическая сложность - O(n), т.е. чем больше элементов в хранилище, тем дольше будет поиск значения. 
Реализованный способ хранения позволяет сделать константный доступ к данным, нужно избавиться от цикла

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/storage/urlrepository.go
> +func (ur *URLRepository) FindByShortenedString(id string) (string, bool, error) {
Нужно стараться не возвращать больше двух значений. В обычной ситуации это значение или значение+ошибка. Если вернуть нужно больше данных, скорее всего лучше возврать структуру (всегда есть исключения)
В данном случае кажется что error  лишний параметр т.к. ошибка только показывает что значение не найдено. О чем говорит и второй параметр, bool

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/service/shorten-service.go
> +func NewShortenService(storage *storage.Storage) *ShortenService {
тут лучше сразу передать конкретный репозиторий
а еще лучше придерживаться такого правила - принимаем интерфейс, отдаем структуру
поэтому давай выше опишем интерфейс и будем принимать его. Тогда будет не важна конкретная реализация - и дальше будет легко подменить эту структуру на другую

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/service/shorten-service.go
> +	return s.storage.Urls().FindByShortenedString(id)
рекомендация: в сигнатуре поле называется id, почему бы так и не назвать метод - FindByID

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/helpers/helpers.go
> +package helpers
helpers слишком размытое понятие, пакет так лучше не называть - получается пакет, который делает все для всех и одновременно ничего. Если хочется выделить методы  и сделать код чище - лучше оставлять такой файл в том же пакете. Например, часто в пакете делают файл types.go и туда выносят структуры или каки-то константы. Те вещи которые к логике не относятся, но в пакете нужны

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/helpers/helpers.go
> +	w.JSON(statusCode, message)
по заданию необходимо возвращать text/plain, будет не очень правильно для ошибки отправлять контент который клиент не  ожидает
а этот метод устанавливает заголовок application/json
кроме того это лишнее усложнение - внутри метода используется маршалинг в json

2023-05-01 20:34 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	log.Fatal(server.Start())
при старте приложения все же лучше возвращать панику т.к. вместе с ней можно увидеть трейс, что может быть полезно для понимания что случилось. А сейчас при ошибке приложение просто завершится

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/handlers.go
> +func (api *API) GetShortenedURL(c *gin.Context) {
лучше не держать все хэндлеры в одном файле - а сделать несколько небольших для каждого. Так они будут небольшие и весь код будет внутри только к ним относиться - в случае если нужно удалить или добавить ручку - это будет происходить в отдельных файлах. Это не вызовет конфликтов при мердже и код будет более понятным. Если ручек станет, например, десять - очивидно читать один файл будет очень сложно

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/handlers_test.go
> +func TestAPI_ShortenURL(t *testing.T) {
лучше делать test tables, в курсе об этом есть материал - читается код гараздо легче и меньше дублирования. Кроме того очень легко добавлять новые кейсы

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/api.go
> +	{
фигурные скобки тут не нужны

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/handlers_test.go
> +//	//assert.EqualValues(t, http.StatusTemporaryRedirect, w.Code)
возможно объяснение будет немного сложным. В юнит тесте мы запускаем голый код с ручкой.  Т.е. мы эмулируем всю оставшуюся часть и сразу запускаем метод с ручкой. В этот момент мы пропускаем некотрую магию, которая происходит в пакете gin

ну так вот в момент когда мы устанавливаем статус с помощью context.Status(), мы устанавливаем его во внутреннюю структуру, не в сам статус writer'а

но после работы нашей ручки, gin проставляет этот статус уже в реальном статусе ответа
с помощью такого метода c.Writer.WriteHeaderNow()

Правильным решением было бы заменить Status() на метод, который предназначен специально для редиректов - c.Redirect(http.StatusTemporaryRedirect, originalURL)
Внутри него есть WriteHeaderNow, поэтому тест заработает как надо

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/storage/urlrepository.go
> +		} else {
логически неверно - если при переборе ссылок, она не равна искомой, сразу вернется негативный результат и перебор остановится. 
Можно попробовать поэксперементировать - создать две которкие ссылки. В текущей реализации либо обе ссылки будут нерабочие, либо только одна. Но обе никогда работать не будут.
Можно на такой кейс добавить тест

2023-05-01 20:34 UTC, maxlyaptsev commented on internal/app/api/api.go
> +package api
я бы вынес этот файл в internal/app - можно назвать например router.go или setup.go 
а директорию можно назвать handlers - тогда тут будут только ручки, а конфигурация и вся эта важная логика будет лежать отдельно. Функционально они очень разные и лучше их в отдном пакете не держать

2023-05-01 21:00 UTC, maxlyaptsev requested changes

2023-05-01 21:00 UTC, maxlyaptsev commented on internal/app/storage/urlrepository.go
> +	u, err := uuid.NewRandom()
лучше storage оставлять максимально глупым - оставить только одну ответсвенность - что-то сохранить и потом это вернуть. Логику генерации корокой ссылки лучше отсуюда вынести

2023-05-01 21:00 UTC, maxlyaptsev commented on internal/app/storage/urlrepository.go
> +	u, err := uuid.NewRandom()
Если такая короткая ссылка уже существует, произойдет замена, а пользователь который получил сокращенную ссылку, начнет получать новую длинную (будет не только обидно, она может содержать например секретный токен)

2023-05-02 08:33 UTC, keyjin88 commented on internal/app/storage/storage.go
> +package storage
Исправлено.

2023-05-02 08:33 UTC, keyjin88 commented on internal/app/storage/storage.go
> +		storage: s,
Исправлено

2023-05-02 08:34 UTC, keyjin88 commented on internal/app/storage/urlrepository.go
> +	for shortenStr, url := range inmemStorage {
Исправлено.

2023-05-02 08:34 UTC, keyjin88 commented on internal/app/storage/urlrepository.go
> +func (ur *URLRepository) FindByShortenedString(id string) (string, bool, error) {
Исправлено.

2023-05-02 08:34 UTC, keyjin88 commented on internal/app/service/shorten-service.go
> +func NewShortenService(storage *storage.Storage) *ShortenService {
Исправлено.

2023-05-02 08:35 UTC, keyjin88 commented on internal/app/service/shorten-service.go
> +	return s.storage.Urls().FindByShortenedString(id)
Исправлено.

2023-05-02 08:37 UTC, keyjin88 commented on internal/app/api/helpers/helpers.go
> +package helpers
Исправлено.

2023-05-02 08:43 UTC, keyjin88 commented on internal/app/api/helpers/helpers.go
> +	w.JSON(statusCode, message)
Исправлено.

2023-05-02 08:44 UTC, keyjin88 commented on cmd/shortener/main.go
> +	log.Fatal(server.Start())
Исправлено.

2023-05-02 08:55 UTC, keyjin88 commented on internal/app/api/api.go
> +	{
Исправлено.

2023-05-02 10:23 UTC, keyjin88 commented on internal/app/api/handlers.go
> +func (api *API) GetShortenedURL(c *gin.Context) {
Исправлено.

2023-05-02 10:23 UTC, keyjin88 commented on internal/app/api/handlers_test.go
> +func TestAPI_ShortenURL(t *testing.T) {
Исправлено.

2023-05-02 10:24 UTC, keyjin88 commented on internal/app/api/handlers_test.go
> +//	//assert.EqualValues(t, http.StatusTemporaryRedirect, w.Code)
Принято. Переписал и все заработало, но все равно пришлось потанцевать с бубном, пока понял, что responseRecoder не перезаписывает статусы.

2023-05-02 10:26 UTC, keyjin88 commented on internal/app/storage/urlrepository.go
> +		} else {
В итоговой реализации этот кейс не воспроизводим, кмк.

2023-05-02 10:26 UTC, keyjin88 commented on internal/app/api/api.go
> +package api
Исправил.

2023-05-02 10:26 UTC, keyjin88 commented on internal/app/storage/urlrepository.go
> +	u, err := uuid.NewRandom()
Исправил.

2023-05-02 11:15 UTC, keyjin88 commented on internal/app/storage/urlrepository.go
> +	u, err := uuid.NewRandom()
Исправлено.

2023-05-02 20:51 UTC, maxlyaptsev commented on internal/app/handlers/getshortenedurl.go
> +		}
Тут можно гараздо проще - в этом и сила сторонних библиотек - они сокращают код и делают его написание легче. Рекомендую если получается много кода и он кажется очень сложным, проверить - нет ли способа сделать это проще

c.String(http.StatusBadRequest, "URL not found ...")

2023-05-02 21:18 UTC, maxlyaptsev requested changes
можно упростить код, а в целом все хорошо

2023-05-02 21:18 UTC, maxlyaptsev commented on internal/app/handlers/getshortenedurl.go
> +package handlers
по желанию - файлы лучше именовать с нижним подчеркивинием - читается легче. Например
get_shortened_url.go
а вот shorten-service.go нужно переименовать, и заменить - на _

2023-05-03 05:19 UTC, keyjin88 commented on internal/app/handlers/getshortenedurl.go
> +		}
Класс. Спасибо. Исправил.

2023-05-03 05:20 UTC, keyjin88 commented on internal/app/handlers/getshortenedurl.go
> +package handlers
Исправлено.

2023-05-03 06:46 UTC, maxlyaptsev approved these changes

2023-05-03 08:20 UTC, merged